name: CI-Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    run_on: ubuntu-lastest
    steps:
      - name: Checkout code
      - uses: actions/checkout@V2
