name: CI-Linter

on:
  push:
  pull_request:
    branches: 
     - master
     - develop
     - release
    
jobs:
  test:
    name: LINTER-CHECKOUT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
